### ISSUE TITLE
onBackgroundMessage Is monitoring acceptable？

### ISSUE THREAD

**Issue by jiushicheng123** [mwaylabs/flutter-apns#104]
connector.configure(
      onLaunch: (data) => onPush('onLaunch', data),
      onResume: (data) => onPush('onResume', data),
      onMessage: (data) => onPush('onMessage', data),
      onBackgroundMessage: _onBackgroundMessage,
    );
onBackgroundMessage Not received  apns Background Notification

**Comment by hatemragab** [comment]
Any updates here?

**Comment by befirst** [comment]
it is because there is no any connection inside flutter_apns_only.dart: https://github.com/mwaylabs/flutter-apns/blob/master/flutter_apns_only/lib/flutter_apns_only.dart#L54

```
/// Sets up [MessageHandler] for incoming messages.
  void configureApns({
    ApnsMessageHandler? onMessage,
    ApnsMessageHandler? onLaunch,
    ApnsMessageHandler? onResume,
    ApnsMessageHandler? onBackgroundMessage,
  }) {
    _onMessage = onMessage;
    _onLaunch = onLaunch;
    _onResume = onResume;
    _channel.setMethodCallHandler(_handleMethod);
    _channel.invokeMethod('configure');
  }
```

**Comment by jiushicheng123** [comment]
ok ,this issues Was solved

**Comment by flodaniel** [comment]
I am using `flutter_apns_only` and this is not yet fixed. The code still looks equal to what @befirst commented. 
Can we reopen this issue?
